{
 "title": "Example - Farm Dashboard By Building",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   { "name": "building", "label": "Building", "query": { "query": "label_values(building)" } }
  ]
 },
 "panels": [
  { "title": "$building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "building" },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (miner_metadata{building='$building'}))",
     "legendFormat": "Miners"
    },
    {
     "expr": "sum(hashboard_nominal_hashrate_gigahashes_per_second{building='$building'})",
     "legendFormat": " Nominal HR"
    },
    {
     "expr": "sum (rate(hashboard_shares{building='$building'}[20s])) * 2^32 / 1e9",
     "legendFormat": "Real HR (10s)"
    }
   ]
  },
  {
   "title": "Total HR",
   "type": "stat",
   "description": "Current real hashrate based on shares from last 10 seconds.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hashboard_shares{building='$building'}[10s])) * 2^32"
    }
   ]
  },
  {
   "title": "Running Miners",
   "type": "stat",
   "description": "Number of miners sending data.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (miner_metadata{building='$building'}))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Average temperature from max temperatures on miner (chip sensor measure or estimate)",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (location) (max by(location, instance) (temperature{location=\"chip\",building='$building'}))",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Power Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(miner_power{type=\"limit\",building='$building'})",
     "legendFormat": "Estimated Power"
    }
   ]
  },
  {
   "title": "Average Fan %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(fan_speed_control{building='$building'})"
    }
   ]
  },
  {
   "title": "Estimated Power",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(miner_power{type=\"estimated\", building=\"$building\"})",
     "legendFormat": "Estimated Power"
    }
   ]
  },
  {
   "title": "Tuner Stage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values (\"Stage\", max by (instance) (tuner_stage{building=\"$building\"}))",
     "legendFormat": "{{Stage}}"
    }
   ]
  }
 ]
}