{
 "title": "Client Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "type", "label": "Hashrate type", "query": "standard,devfee" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Version of Farm Proxy",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FP_application_version_details", "legendFormat": "Version: {{version_full}}" }
   ]
  },
  {
   "title": "Braiins Product Stack",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<table width=\"100%\" style:\" border: none !important; table-layout: fixed; \" id=\"bps-table\">\n<tr>\n<td style=\"text-align: center; padding: 16px 0; width:50%;\"><a href=\"https://braiins.com/os/plus?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\"><img src=\"https://design.braiins.com/assets/img/logos/braiins-os-plus-logo-reverse-rgb.svg?h=d35e19f3056bef1664b2c5cbde453a44\" height=\"25px\" align=\"center\"></a></td>\n<td style=\"text-align: center; padding: 16px 0; width:50%;\"><a href=\"https://slushpool.com/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\"><img src=\"https://design.braiins.com/assets/img/logos/slushpool-logo-reverse-rgb.svg?h=6e9e1089b4b55194f400c37f6482f7e7\" height=\"25px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 16px 0;\"><a href=\"https://stratumprotocol.org/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/stratum-v2-logo-reverse-rgb.svg?h=77e94750d6f57e33cf70c51e07e5aac5\" height=\"14px\"></a></td>\n<td style=\"text-align: center; padding: 16px 0;\"><a href=\"https://insights.braiins.com/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/braiins-insights-logo-on-dark-background-rgb.svg?h=aad9d059abab45e38f162e05c1fa322f\" height=\"17px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 16px 0;\" colspan=\"2\"><a href=\"https://braiins.com/farm-proxy/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/farm-proxy-logo-white-rgb.svg?h=3e5188e1d46f58ccb0b910c6f8184b9b\" height=\"30px\"></a></td>\n</tr>\n</table>"
   }
  },
  {
   "type": "stat",
   "description": "Most recent Farm Proxy start date",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FP_start_time_ms", "legendFormat": "started at:" },
    {}
   ]
  },
  {
   "title": "Downstream hashrate",
   "type": "stat",
   "description": "Hashrate received from miners.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "stat",
   "description": "Hashrate sent to target pool(s).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "title": "Downstream shares",
   "type": "stat",
   "description": "Shares received from miners",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=\"$type\"})",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status!=\"accepted\", type=\"$type\"})",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status!=\"accepted\", type=\"$type\"}) / sum(FP_shares_total{direction=\"downstream\", type=\"$type\"}) * 100",
     "legendFormat": "Invalid ratio"
    }
   ]
  },
  {
   "title": "Upstream shares",
   "type": "stat",
   "description": "Shares sent to target pool(s).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status=\"validated\",type=\"$type\"})",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status!=\"validated\",type=\"$type\"})",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status!=\"validated\",type=\"$type\"}) / sum(FP_shares_total{direction=\"upstream\", type=\"$type\"}) * 100",
     "legendFormat": "Invalid ratio"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "stat",
   "description": "Count of currently connected miners by hashrate type",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Upstream connections",
   "type": "stat",
   "description": "Count of connections to target pool(s) by hashrate type",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Downstream hashrate",
   "type": "timeseries",
   "description": "Hashrate received from miners",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[5m]) * 4.294967296) by (type)",
     "legendFormat": "{{type}} hashrate (accepted)"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status!=\"accepted\", type=~\"$type\"}[1m]) * 4.294967296) by (type)",
     "legendFormat": "{{type}} hashrate (invalid)"
    }
   ]
  },
  {
   "title": "Aggregation",
   "type": "stat",
   "description": "Theoretical aggregation based on ratio of upstream and downstream connections. Theoretical means the real aggregation can be lower due to network events (e.g. reconnections or job resets).",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Aggregation history",
   "type": "timeseries",
   "description": "History of theoretical aggregation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "timeseries",
   "description": "Hashrate sent to target pool(s)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[5m]) * 4.294967296) by (type)",
     "legendFormat": "{{type}} hashrate (accepted)"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status!=\"validated\", type=~\"$type\"}[1m]) * 4.294967296) by (type)",
     "legendFormat": "{{type}} hashrate (invalid)"
    }
   ]
  },
  {
   "title": "Hashrate split",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Split among goals",
     "type": "piechart",
     "description": "Split of standard hashrate among defined goals.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100* sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"}) by (goal) / ignoring(goal) group_left sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"})",
       "legendFormat": "{{goal}}"
      }
     ]
    },
    {
     "title": "Split among targets",
     "type": "piechart",
     "description": "Split of standard hashrate among targets (IP addresses behind pool URL).",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=\"standard\"}[5m])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  }
 ]
}