{
 "title": "Client Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "type", "label": "Hashrate type", "query": "standard,devfee" }
  ]
 },
 "panels": [
  {
   "title": "Downstream hashrate",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FP_application_version_details", "legendFormat": "Version: {{version_full}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FP_start_time_ms", "legendFormat": "started at:" },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FP_remaining_certificate_validity_days",
     "legendFormat": "Certificate valid for:"
    }
   ]
  },
  {
   "title": "Downstream shares",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=\"$type\"})",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status=\"invalid\", type=\"$type\"})",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"downstream\", status=\"invalid\", type=\"$type\"}) / sum(FP_shares_total{direction=\"downstream\", type=\"$type\"}) * 100",
     "legendFormat": "Invalid ratio"
    }
   ]
  },
  {
   "title": "Upstream shares",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status=\"validated\",type=\"$type\"})",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status=\"rejected\",type=\"$type\"})",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum(FP_shares_total{direction=\"upstream\", status=\"rejected\",type=\"$type\"}) / sum(FP_shares_total{direction=\"upstream\", type=\"$type\"}) * 100",
     "legendFormat": "Invalid ratio"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Upstream connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Downstream hashrate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"accepted\", type=~\"$type\"}[5m]) * 4.294967296) by (status, type)",
     "legendFormat": "{{type}} hashrate ({{status}})"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"downstream\", status=\"invalid\", type=~\"$type\"}[1m]) * 4.294967296) by (status, type)",
     "legendFormat": "{{type}} hashrate ({{status}})"
    }
   ]
  },
  {
   "title": "Aggregation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Aggregation history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=~\"$type\"}[5m]) * 4.294967296) by (status, type)",
     "legendFormat": "{{type}} hashrate (accepted)"
    },
    {
     "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"rejected\", type=~\"$type\"}[1m]) * 4.294967296) by (status, type)",
     "legendFormat": "{{type}} hashrate (invalid)"
    }
   ]
  },
  {
   "title": "Hashrate split",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Split among goals",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100* sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"}) by (goal) / ignoring(goal) group_left sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"})",
       "legendFormat": "{{goal}}"
      }
     ]
    },
    {
     "title": "Split among targets",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_shares_total{direction=\"upstream\", status=\"validated\", type=\"standard\"}[5m])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  }
 ]
}