{
 "title": "Debug Dashboard FP",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "status",
    "query": {
     "query": "label_values(FP_shares_total, status)"
    }
   },
   { "name": "direction", "query": "upstream,downstream" },
   {
    "name": "server",
    "query": {
     "query": "label_values(FP_shares_total{direction=\"downstream\"}, server)"
    }
   },
   { "name": "type", "query": "standard,devfee" },
   {
    "name": "target",
    "query": {
     "query": "label_values(FP_connections_by_target, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FP_start_time_ms",
     "legendFormat": "Router start time - {{instance}}:"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_shares_total{direction=~\"$direction\",status=~\"$status\", type=~\"$type\"}[5m]) * 4.294967296) by (server, direction, status, type)",
     "legendFormat": "{{server}} {{status}} {{direction}} {{type}} hashrate"
    }
   ]
  },
  {
   "title": "Certificate validity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FP_remaining_certificate_validity_days",
     "legendFormat": "instance: {{instance}} "
    }
   ]
  },
  {
   "title": "Connection",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{target=~\"$target\"}) + sum(FP_subscription_size_to_target_total{target=~\"$target\"})",
     "legendFormat": "#active connections"
    },
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "upstream standard open connection"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "downstream standard open connection"
    },
    {
     "expr": "sum(FP_connections_by_target{goal=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "upstream devfee open connection"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "downstream devfee open connection"
    }
   ]
  },
  {
   "title": "Submission Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(FP_submits_total{direction=~\"$direction\",status=~\"$status\", type=~\"$type\"}[1m])) by (server, direction, status, type)",
     "legendFormat": "{{server}} {{status}} {{direction}} {{type}} submits"
    }
   ]
  },
  {
   "title": "Hashrate Split",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100* sum(FP_shares_total{direction=\"upstream\",server=~\"$target\", type=\"standard\"}) by (server) / ignoring(server) group_left sum(FP_shares_total{direction=\"upstream\", type=\"standard\"})",
     "legendFormat": "standard {{server}}"
    },
    {
     "expr": "100* sum(FP_shares_total{direction=\"upstream\",server=~\"$target\", type=\"devfee\"}) by (server) / ignoring(server) group_left sum(FP_shares_total{direction=\"upstream\", type=\"devfee\"})",
     "legendFormat": "devfee {{server}}"
    }
   ]
  },
  {
   "title": "HR split - detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated HR",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "THs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_allocated_hash_rate_by_providers[1m]) * 4.294967296)  by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Hashrate Split",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100* sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"}) by (goal) / ignoring(goal) group_left sum(FP_hash_rate_by_providers{goal!=\"#!!ii-DevFee\"})",
       "legendFormat": "{{goal}}"
      }
     ]
    },
    {
     "title": "HashRate from Receivers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "THs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_hash_rate_by_receivers[1m])* 4.294967296)"
      }
     ]
    },
    {
     "title": "Measured HR on targets",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "THs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_hash_rate_by_providers[1m])* 4.294967296) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Hashrate Split - devfee",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100* sum(FP_hash_rate_by_providers{goal=\"#!!ii-DevFee\"}) by (goal) / ignoring(goal) group_left sum(FP_hash_rate_by_providers{goal=\"#!!ii-DevFee\"})",
       "legendFormat": "{{goal}}"
      }
     ]
    }
   ]
  },
  { "title": "Connection metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connection to upstream",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{target=~\"$target\"}) by (target, goal)",
     "legendFormat": "{{goal}} {{target}}"
    }
   ]
  },
  {
   "title": "Subscription by target - devfee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\",target=~\"$target\"}) by (goal, target)",
     "legendFormat": "{{goal}} - {{target}}"
    }
   ]
  },
  {
   "title": "Subscription by target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\",target=~\"$target\"}) by (goal, target)",
     "legendFormat": "{{goal}} - {{target}}"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(FP_mean_latency_s{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Std dev latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(FP_std_dev_latency_s{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Rejection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(FP_rejection_rate{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(FP_error_rate{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Target Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_target_status) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Router metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Score by target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(FP_score_by_target{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Timeout counter v1 upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(rate(FP_upstream_request_timeout_queue[10m])) by (type)"
    }
   ]
  },
  {
   "title": "V1 upstream queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(rate(FP_upstream_request_queue[10m]))",
     "legendFormat": "#request in Upstream queue"
    },
    {
     "expr": "sum(rate(FP_upstream_request_timeout_queue[10m]))",
     "legendFormat": "#timeout request in Upstream queue"
    }
   ]
  },
  {
   "title": "Waiting queue monitoring",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_buffers_sizes) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Providerds to remove",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_provider_to_remove_size) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Job submits map size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum(increase(FP_job_submits_size[10m]))"
    }
   ]
  },
  {
   "title": "Job queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum(increase(FP_job_queue_size[10m]))"
    }
   ]
  },
  {
   "title": "Old jobs detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(increase(FP_old_jobs[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}