{
 "title": "Farm Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"braiinsos-data\"})",
     "legendFormat": "Miners"
    },
    {
     "expr": "sum(hashboard_nominal_hashrate_gigahashes_per_second)",
     "legendFormat": " Nominal HR"
    },
    {
     "expr": "sum (rate(hashboard_shares[20s])) * 2^32 / 1e9",
     "legendFormat": "Real HR (10s)"
    }
   ]
  },
  {
   "title": "Miner Status",
   "type": "stat",
   "description": "Summary of high-level status of individual miners.",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"braiinsos-data\"})",
     "legendFormat": "Defined Miners"
    },
    {
     "expr": "count(up{job=\"braiinsos-data\"} == 1)",
     "legendFormat": "Responsive Miners"
    },
    {
     "expr": "count(sum by (instance) (rate(hashboard_shares[60s])) > 0)",
     "legendFormat": "Mining"
    },
    {
     "expr": "count(max by (instance) (rate(hashboard_shares[60s]) or up{job=\"braiinsos-data\"} * 0) == 0)",
     "legendFormat": "Not Mining"
    }
   ]
  },
  {
   "title": "Braiins Product Stack",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<table width=\"100%\" style:\" border: none !important; table-layout: fixed; \" id=\"bps-table\">\n<tr>\n<td style=\"text-align: center; padding: 16px 0; width:50%;\"><a href=\"https://braiins.com/os/plus?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\"><img src=\"https://design.braiins.com/assets/img/logos/braiins-os-plus-logo-reverse-rgb.svg?h=d35e19f3056bef1664b2c5cbde453a44\" height=\"25px\" align=\"center\"></a></td>\n<td style=\"text-align: center; padding: 16px 0; width:50%;\"><a href=\"https://slushpool.com/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\"><img src=\"https://design.braiins.com/assets/img/logos/slushpool-logo-reverse-rgb.svg?h=6e9e1089b4b55194f400c37f6482f7e7\" height=\"25px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 16px 0;\"><a href=\"https://stratumprotocol.org/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/stratum-v2-logo-reverse-rgb.svg?h=77e94750d6f57e33cf70c51e07e5aac5\" height=\"14px\"></a></td>\n<td style=\"text-align: center; padding: 16px 0;\"><a href=\"https://insights.braiins.com/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/braiins-insights-logo-on-dark-background-rgb.svg?h=aad9d059abab45e38f162e05c1fa322f\" height=\"17px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 16px 0;\" colspan=\"2\"><a href=\"https://braiins.com/farm-proxy/?utm_source=Grafana&utm_medium=Dashboard_panel\"  target=\"_blank\" style=\"display:block\"><img src=\"https://design.braiins.com/assets/img/logos/farm-proxy-logo-white-rgb.svg?h=3e5188e1d46f58ccb0b910c6f8184b9b\" height=\"30px\"></a></td>\n</tr>\n</table>"
   }
  },
  {
   "title": "Average Fan %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(fan_speed_control)" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Average temperature from max temperatures on miner (chip sensor measure or estimate)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (location) (max by(location, instance) (temperature{location=\"chip\"}))",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Total HR",
   "type": "stat",
   "description": "Current real hashrate based on shares from last 10 seconds.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hashboard_shares[10s])) * 2^32"
    }
   ]
  },
  {
   "title": "Power Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(miner_power{type=\"limit\"})",
     "legendFormat": "Estimated Power"
    }
   ]
  },
  {
   "title": "Client Status - Active (Mining) Pools",
   "type": "bargauge",
   "description": "Status of individual defined pool connections",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((count_values('x',client_status{connection_type=\"user\"} > 0) by (host)))",
     "legendFormat": "{{host}} "
    }
   ]
  },
  {
   "title": "Estimated Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(miner_power{type=\"estimated\"})",
     "legendFormat": "Estimated Power"
    }
   ]
  },
  {
   "title": "Client Status - Dead Pools",
   "type": "bargauge",
   "description": "Status of individual defined pool connections",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((count_values('x',client_status{connection_type=\"user\"} < 0) by (host))) # ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Tuner Stage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values (\"Stage\", max by (instance) (tuner_stage))\n\n#max by (instance) (tuner_stage)\n",
     "legendFormat": "{{Stage}}"
    }
   ]
  },
  {
   "title": "10 Miners with lowest MCR",
   "type": "bargauge",
   "description": "20  seconds MCR is calculated and miners with lowest result are shown. Links are on IP address.",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bottomk(10, \n    sort(\n        sum by (building, instance) (rate(hashboard_shares[20s])) * 2^32\n        /\n        sum by(building, instance) (hashboard_nominal_hashrate_gigahashes_per_second * 1e9)\n    )\n)",
     "legendFormat": "{{building}} {{instance}}"
    }
   ]
  },
  {
   "title": "Less Than 3 HBs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(instance) (rate(hashboard_shares{type=\"valid\"}[20s]) > 0) <3)"
    }
   ]
  },
  {
   "title": "Temperature Top 10 Instances",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10,sort_desc(max by(building, instance) (temperature)))",
     "legendFormat": "{{building}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Miners by Site/Subnet",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "count(miner_metadata) by(site_id, subnet_id)"
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Real HR, Nominal HR",
   "type": "timeseries",
   "description": "Real and Nominal Hashrate",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(hashboard_shares[10s])) * 2^32",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(hashboard_nominal_hashrate_gigahashes_per_second) * 1e9",
     "legendFormat": "Nominal Hashrate"
    }
   ]
  },
  {
   "title": "Running Miners",
   "type": "timeseries",
   "description": "Number of miners sending data.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (instance) (miner_metadata))",
     "legendFormat": "Running Miners"
    }
   ]
  },
  {
   "title": "Min, Avg, Max Temperature",
   "type": "timeseries",
   "description": "Maximum temperature is taken from each instance (miner).  Minimum, Average, and Maximum is then calculated.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(max by (instance) (temperature))",
     "legendFormat": "Avg Temperature"
    },
    {
     "expr": "max(max by (instance) (temperature))",
     "legendFormat": "Max Temperature"
    },
    {
     "expr": "min(max by (instance) (temperature))",
     "legendFormat": "Min Temperature"
    }
   ]
  },
  {
   "title": "Power Limit & Est. Consumption (W)",
   "type": "timeseries",
   "description": "Estimated power consumption in Watts and power limit.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(miner_power{type=\"estimated\"})",
     "legendFormat": "Estimated Power (W)"
    },
    {
     "expr": "sum(miner_power{type=\"limit\"})",
     "legendFormat": "Power Limit (W)"
    }
   ]
  },
  {
   "title": "Min, Avg, Max Fan Speed",
   "type": "timeseries",
   "description": "Maximum temperature is taken from each instance (miner).  Minimum, Average, and Maximum is then calculated.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(max by (instance) (fan_speed_control))",
     "legendFormat": "Avg Fan Speed"
    },
    {
     "expr": "max(max by (instance) (fan_speed_control))",
     "legendFormat": "Max Fan Speed"
    },
    {
     "expr": "min(max by (instance) (fan_speed_control))",
     "legendFormat": "Min Fan Speed"
    }
   ]
  },
  {
   "title": "Min, Avg, Max Power Limit",
   "type": "timeseries",
   "description": "Power limit is taken from each instance (miner).  Minimum, Average, and Maximum is then calculated.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(max by (instance) (miner_power{type=\"limit\"}))",
     "legendFormat": "Avg Temperature"
    },
    {
     "expr": "max(max by (instance) (miner_power{type=\"limit\"}))",
     "legendFormat": "Max Temperature"
    },
    {
     "expr": "min(max by (instance) (miner_power{type=\"limit\"}))",
     "legendFormat": "Min Temperature"
    }
   ]
  },
  {
   "title": "Prometheus Status",
   "type": "timeseries",
   "description": "Number of instances that are scraped successfully (Up) or not (Down).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "count_values(\"Status\",up{job!=\"prometheus\"})",
     "legendFormat": "{{Status}}"
    }
   ]
  },
  {
   "title": "Tuner Status",
   "type": "timeseries",
   "description": "Tuner Status - in case of per-hashboard tuning, maximum status is used.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "count_values(\"TunerStatus\", max by(instance) (tuner_stage))",
     "legendFormat": "{{TunerStatus}}"
    }
   ]
  },
  {
   "title": "Dead Pools",
   "type": "timeseries",
   "description": "Dead Pools",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "count_values(\"Status\", client_status < 0) by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Miners count by model",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (model)(miner_metadata)",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Power Limit",
   "type": "stat",
   "description": "Power Limit of Miners",
   "gridPos": { "h": 14, "w": 3, "x": 5, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values (\"PowerLimit\", max by (instance) (miner_power{type=\"limit\"}))",
     "legendFormat": "{{PowerLimit}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (os_version) (miner_metadata)",
     "legendFormat": "{{os_version}}"
    }
   ]
  }
 ]
}